# Generated by Django 5.0.7 on 2024-08-03 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_school_alter_student_joining_class_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='school_name',
            new_name='school',
        ),
    ]
