# Generated by Django 5.0.7 on 2024-08-05 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0004_alter_batch_level'),
        ('core', '0004_currentclass'),
        ('students', '0004_currentclass_alter_student_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.currentclass'),
        ),
        migrations.DeleteModel(
            name='CurrentClass',
        ),
    ]
