# Generated by Django 5.0.7 on 2024-07-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='success_students')),
                ('school', models.CharField(max_length=255)),
                ('current_class', models.CharField(max_length=50)),
                ('success', models.CharField(max_length=255)),
            ],
        ),
    ]
