# Generated by Django 5.0.7 on 2024-08-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_successstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.TextField(blank=True, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
