# Generated by Django 5.0.7 on 2024-09-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexammark',
            name='marks',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
