# Generated by Django 5.0.7 on 2024-07-31 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='day',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='batch',
            name='level',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='batch',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='batches', to='students.student'),
        ),
    ]
