# Generated by Django 5.0.7 on 2024-08-05 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0002_batch_day_batch_level_alter_batch_students'),
        ('students', '0004_currentclass_alter_student_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.currentclass'),
        ),
    ]
