# Generated by Django 5.0.7 on 2024-08-05 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0003_alter_batch_level'),
        ('core', '0004_currentclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.currentclass'),
        ),
    ]
